#define LINUX 1
#define HAS_STDINT_H 1
#define HAS_INTTYPES_H 1
#define HAVE_IPV6 1
#define _GNU_SOURCE 1
#define HAVE_IN6_PKTINFO 1
#define HAVE_SYS_TIMEPPS_H 1
#define HAVE_PPSAPI 1
#define FEAT_LINUXCAPS 1
#define FEAT_RTC 1
#define HAVE_SCHED_SETSCHEDULER 1
#define HAVE_MLOCKALL 1
#define FORCE_DNSRETRY 1
#define FEAT_READLINE 1
#define USE_EDITLINE 1
#define GENERATE_SHA1_KEY 1
#define DEFAULT_CONF_FILE "/etc/chrony.conf"
#define MAIL_PROGRAM "/usr/lib/sendmail"
#define CHRONY_VERSION "1.29"
