#!/bin/sh
set -e
# postrm for chrony John Hasler 1998-2006
# Any possessor of a copy of this program may treat it as if it
# were in the public domain.  I waive all rights.
rm -f /var/lib/chrony/*
if [ -x update-menus ] ; then 
	update-menus
fi

if [ "$1" = "purge" ] ; then
    rm -rf /etc/chrony/chrony.conf
    if which ucf >/dev/null; then
	ucf --purge /etc/chrony/chrony.conf
    fi
    if which ucfr >/dev/null; then
	ucfr --purge chrony /etc/chrony/chrony.conf
    fi
    rm -rf /var/lib/chrony
    rm -rf /usr/share/chrony
    rm -rf /var/log/chrony
    rm -rf /etc/cron.weekly/chrony
    rm -rf /etc/ppp/ip-up.d/chrony
    rm -rf /etc/ppp/ip-down.d/chrony
    rm -rf /etc/chrony
    update-rc.d chrony remove >/dev/null
fi
