#!/bin/sh
set -e
# preinst for Chrony  John G. Hasler jhasler@debian.org 2006
# Any possessor of a copy of this program may treat it as if it
# were in the public domain.  I waive all rights.

case "$1" in
    install|upgrade)

# If we are upgrading from an old version protect the keys and
# conf files from dpkg.

        if dpkg --compare-versions "$2" lt-nl 1.21-3 ; then
            mv /etc/chrony/chrony.keys /etc/chrony/chrony.keys."$2"
	    mv /etc/chrony/chrony.conf /etc/chrony/chrony.conf."$2"
        fi
    ;;

    *)
        exit 0
    ;;
esac
exit 0
