#!/bin/sh
set -e
# Automatically added by dh_installinit
# install-info --quiet --remove /usr/share/info/chrony.info.gz
invoke-rc.d chrony stop
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/chrony ]; then
     rm -f /usr/doc/chrony
fi
# End automatically added section
